import type { GlossaryKey } from './glossary';

/**
 * Términos técnicos que, si aparecen en una pestaña de un algoritmo, deben
 * llevar su ficha 💡 (<G k>) al menos una vez en esa pestaña.
 * Reglas de fichas: al menos una por pestaña (glossaryTerms.test) y como máximo 3 por
 * bloque <p>/<li> (glossaryDensity.test): si un término ya tiene ficha antes en la
 * misma pestaña se quita de la frase; si no, se parte la frase en dos párrafos.
 * Las regex van sin bandera: el test les añade `iu` y límites de palabra.
 */
export interface RequiredTerm {
  re: string;
  key: GlossaryKey;
  /** Fichas más específicas que ya explican el término («kernel RBF» explica «kernel»). */
  alsoBy?: GlossaryKey[];
}

export const REQUIRED_TERMS: readonly RequiredTerm[] = [
  { re: 'features?', key: 'feature' },
  { re: 'datasets?', key: 'dataset' },
  { re: 'overfitting|sobreajust\\p{L}*', key: 'overfitting' },
  { re: 'regularización', key: 'regularizacion', alsoBy: ['regularizacionL1L2'] },
  { re: 'L1|L2|Lasso|Ridge', key: 'regularizacionL1L2' },
  { re: 'kernels?', key: 'kernel', alsoBy: ['rbf', 'filtro'] },
  { re: 'embeddings?', key: 'embedding' },
  { re: 'umbral(es)?|thresholds?', key: 'umbral' },
  { re: 'descenso (de|por) gradiente', key: 'descensoGradiente' },
  { re: '(?<!descenso (?:de|por) )gradientes?', key: 'gradiente', alsoBy: ['desvanecimiento', 'retropropagacion'] },
  { re: 'solvers?', key: 'solver' },
  { re: 'bootstrap', key: 'bootstrap' },
  { re: 'ensambles?', key: 'ensamble' },
  { re: 'batch(es)?|mini-?lotes?', key: 'batch' },
  { re: 'hiperparámetros?', key: 'hiperparametro' },
  { re: 'validación cruzada', key: 'validacionCruzada' },
  { re: '(?<!log-)odds', key: 'odds' },
  { re: 'log-odds', key: 'logOdds' },
  { re: 'residuos?', key: 'residuo' },
  { re: 'MSE', key: 'mse' },
  { re: 'R²', key: 'r2' },
  { re: 'outliers?|valor(es)? atípicos?', key: 'outlier' },
  { re: 'sigmoide', key: 'sigmoide' },
  { re: 'softmax', key: 'softmax' },
  { re: 'PCA', key: 'pca' },
  { re: 'Gini', key: 'gini' },
  { re: 'entropía', key: 'entropia' },
  { re: 'ROC|AUC', key: 'rocAuc' },
  { re: 'exactitud|accuracy', key: 'exactitud' },
  { re: 'bagging', key: 'bagging' },
  { re: 'OOB|out-of-bag', key: 'oob' },
  { re: '(?<!Gradient )boosting', key: 'boosting' },
  { re: 'tasa de aprendizaje|learning rate', key: 'tasaAprendizaje' },
  { re: 'early stopping|parada temprana', key: 'paradaTemprana' },
  { re: 'SHAP', key: 'shap' },
  { re: 'Huber', key: 'huber' },
  { re: 'hiperplanos?', key: 'hiperplano' },
  { re: 'vectores de soporte|vector de soporte', key: 'vectorSoporte' },
  { re: 'matriz de confusión', key: 'matrizConfusion' },
  { re: 'log loss|pérdida logarítmica', key: 'perdidaLog' },
  { re: 'frontera de decisión', key: 'frontera' },
  { re: 'XGBoost|LightGBM|CatBoost', key: 'bibliotecasBoosting' },
  { re: 'Transformers?', key: 'transformer' },
  { re: 'redes convolucionales|red convolucional', key: 'redConvolucional' },
  { re: 'redes neuronales|red neuronal', key: 'redNeuronal' },
  { re: 'RBF', key: 'rbf' },
  { re: 'SMO|LIBSVM', key: 'smo' },
  { re: 'SVR', key: 'svr' },
  { re: 'bigramas?|n-gramas?', key: 'ngrama' },
  { re: 'escalad[oa]s?(?! de Platt)|estandariza\\p{L}*', key: 'escalado' },
  { re: 'valores faltantes|NaN', key: 'faltantes' },
  { re: 'datos tabulares|tabular(es)?', key: 'tabular' },
  { re: 'clases desbalanceadas|desbalance', key: 'desbalance' },
  { re: 'extrapola\\p{L}*', key: 'extrapolar' },
  { re: 'calibra\\p{L}*', key: 'calibracion' },
  { re: 'clusters?|clústeres?', key: 'cluster' },
  { re: 'centroides?', key: 'centroide' },
  { re: 'inercia', key: 'inercia' },
  { re: 'silueta', key: 'silueta' },
  { re: 'método del codo', key: 'codo' },
  { re: 'k-means\\+\\+', key: 'kmeansPP' },
  { re: 'dendrogramas?', key: 'dendrograma' },
  { re: 'linkage|enlace (simple|completo|promedio)|Ward', key: 'enlace' },
  { re: 'cofenética', key: 'cofenetica' },
  { re: 'componentes? principal(es)?', key: 'componentePrincipal', alsoBy: ['pca'] },
  { re: 'varianza (explicada|retenida)', key: 'varianzaExplicada' },
  { re: 'autovectores?|autovalores?', key: 'autovector' },
  { re: 'error de reconstrucción', key: 'reconstruccion' },
  { re: 'minPts|min_samples', key: 'minPts' },
  { re: 'puntos? (núcleo|de borde)', key: 'puntoNucleo' },
  { re: 'haversine', key: 'haversine' },
  { re: 'HDBSCAN', key: 'hdbscan' },
  { re: 't-SNE|UMAP', key: 'tsneUmap' },
  { re: 'neuronas?', key: 'neurona' },
  { re: 'capas? ocultas?', key: 'capaOculta' },
  { re: 'funci(ón|ones) de activación', key: 'funcionActivacion', alsoBy: ['relu'] },
  { re: 'ReLU', key: 'relu' },
  { re: 'retropropaga\\p{L}*|backpropagation', key: 'retropropagacion' },
  { re: 'épocas?', key: 'epoca' },
  { re: 'XOR', key: 'xor' },
  { re: 'convolución|convoluciones', key: 'convolucion' },
  { re: 'mapas? de activación|feature maps?', key: 'mapaActivacion' },
  { re: '(max )?pooling', key: 'pooling' },
  { re: 'aumento de datos|data augmentation', key: 'aumentoDatos' },
  { re: 'aprendizaje por transferencia|transfer learning|fine-tuning|ajuste fino', key: 'transferencia' },
  { re: 'estados? ocultos?', key: 'estadoOculto' },
  { re: 'desvanec\\p{L}*', key: 'desvanecimiento' },
  { re: 'LSTM|GRU', key: 'lstm' },
  { re: 'autosupervisad\\p{L}*', key: 'autosupervisado' },
  { re: 'tokens?', key: 'token' },
  { re: 'self-attention|autoatención|mapas? de atención|mecanismo de atención', key: 'atencion' },
  { re: 'codificación posicional', key: 'codificacionPosicional' },
  { re: 'máscara causal', key: 'mascaraCausal' },
  { re: 'BERT|GPT', key: 'bertGpt' },
  { re: 'LLMs?|ChatGPT|modelos? de lenguaje grandes?', key: 'llm' },
  { re: 'alucina\\p{L}*', key: 'alucinacion' },
  { re: 'autoencoders?', key: 'autoencoder' },
  { re: 'cuellos? de botella', key: 'cuelloBotella' },
  { re: 'anomalías?', key: 'anomalia' },
  { re: 'GPUs?', key: 'gpu' },
  { re: 'PyTorch|TensorFlow|Keras', key: 'pytorch' },
  { re: 'dropout', key: 'dropout' },
];

/** Regex lista para buscar el término como palabra completa. */
export function termRegExp(re: string): RegExp {
  return new RegExp(`(?<![\\p{L}\\p{N}_-])(?:${re})(?![\\p{L}\\p{N}_])`, 'iu');
}
